// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * Connection 客户端连接配置档案，用于连接外部（或本地）MQTT broker。
 */
export interface Connection {
    "id": string;
    "name": string;

    /**
     * tcp | ws | tls | wss
     */
    "protocol": string;
    "host": string;
    "port": number;

    /**
     * WebSocket 路径，如 /mqtt
     */
    "path": string;

    /**
     * 为空时连接时自动生成
     */
    "clientId": string;
    "username": string;
    "password": string;

    /**
     * 秒
     */
    "keepAlive": number;
    "cleanSession": boolean;

    /**
     * 3=3.1, 4=3.1.1
     */
    "mqttVersion": number;
    "tlsSkipVerify": boolean;
    "sortOrder": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
}
