// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * Connection 客户端连接配置档案，用于连接外部（或本地）MQTT broker。
 */
export interface Connection {
    "id": string;
    "name": string;

    /**
     * tcp | ws | tls | wss
     */
    "protocol": string;
    "host": string;
    "port": number;

    /**
     * WebSocket 路径，如 /mqtt
     */
    "path": string;

    /**
     * 为空时连接时自动生成
     */
    "clientId": string;
    "username": string;
    "password": string;

    /**
     * 秒
     */
    "keepAlive": number;
    "cleanSession": boolean;

    /**
     * 3=3.1, 4=3.1.1
     */
    "mqttVersion": number;
    "tlsSkipVerify": boolean;
    "sortOrder": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
}

/**
 * ConnectionInput 是保存连接档案时前端提交的入参。
 * 刻意不含 CreatedAt/UpdatedAt —— 时间戳由后端管理，前端无需（也不应）传递，
 * 从而避免把空字符串反序列化为 time.Time 时的解析错误。
 */
export interface ConnectionInput {
    /**
     * 为空表示新建
     */
    "id": string;
    "name": string;
    "protocol": string;
    "host": string;
    "port": number;
    "path": string;
    "clientId": string;
    "username": string;
    "password": string;
    "keepAlive": number;
    "cleanSession": boolean;
    "mqttVersion": number;
    "tlsSkipVerify": boolean;
    "sortOrder": number;
}
