// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrokerService 管理内嵌的 mochi-mqtt broker 生命周期。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearEvents 清空活动日志缓存。
 */
export function ClearEvents(): $CancellablePromise<void> {
    return $Call.ByID(2870773168);
}

/**
 * GetClients 返回当前已连接的客户端列表（不含内嵌客户端）。
 */
export function GetClients(): $CancellablePromise<$models.BrokerClientInfo[] | null> {
    return $Call.ByID(4122937796);
}

/**
 * GetConfig 返回当前（持久化的）broker 配置。
 */
export function GetConfig(): $CancellablePromise<$models.BrokerConfig> {
    return $Call.ByID(2165266174);
}

/**
 * GetRecentEvents 返回最近的 broker 活动日志（最新在前）。
 */
export function GetRecentEvents(): $CancellablePromise<$models.BrokerEvent[] | null> {
    return $Call.ByID(474137198);
}

/**
 * GetStatus 返回 broker 的当前状态与统计。
 */
export function GetStatus(): $CancellablePromise<$models.BrokerStatus> {
    return $Call.ByID(3599088338);
}

/**
 * IsRunning 返回 broker 是否正在运行。
 */
export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(3862892459);
}

/**
 * PublishFromBroker 以内嵌客户端身份直接发布一条消息（用于服务端主动下发调试）。
 */
export function PublishFromBroker(topic: string, payload: string, qos: number, retain: boolean): $CancellablePromise<void> {
    return $Call.ByID(3754683046, topic, payload, qos, retain);
}

/**
 * SaveConfig 持久化 broker 配置（不影响正在运行的实例，需重启生效）。
 */
export function SaveConfig(cfg: $models.BrokerConfig): $CancellablePromise<void> {
    return $Call.ByID(3159898163, cfg);
}

/**
 * Start 使用给定配置启动 broker。配置会被持久化。
 */
export function Start(cfg: $models.BrokerConfig): $CancellablePromise<void> {
    return $Call.ByID(2958310680, cfg);
}

/**
 * Stop 停止正在运行的 broker。
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(1408561852);
}
