// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClientService 管理多个 paho MQTT 客户端连接。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Connect 建立一个客户端连接。若同 connID 已存在连接，会先断开。
 */
export function Connect(connID: string, opts: $models.ClientConnectOptions): $CancellablePromise<void> {
    return $Call.ByID(1066653600, connID, opts);
}

/**
 * Disconnect 断开并移除指定连接。
 */
export function Disconnect(connID: string): $CancellablePromise<void> {
    return $Call.ByID(3055236036, connID);
}

/**
 * DisconnectAll 断开所有客户端连接（应用退出时调用）。
 */
export function DisconnectAll(): $CancellablePromise<void> {
    return $Call.ByID(839832639);
}

/**
 * IsConnected 返回指定连接是否处于活动状态。
 */
export function IsConnected(connID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2085283493, connID);
}

/**
 * Publish 发布一条消息。
 */
export function Publish(connID: string, topic: string, payload: string, qos: number, retain: boolean): $CancellablePromise<void> {
    return $Call.ByID(2288480441, connID, topic, payload, qos, retain);
}

/**
 * Subscribe 订阅一个主题。
 */
export function Subscribe(connID: string, topic: string, qos: number): $CancellablePromise<void> {
    return $Call.ByID(1571083678, connID, topic, qos);
}

/**
 * Unsubscribe 取消订阅一个主题。
 */
export function Unsubscribe(connID: string, topic: string): $CancellablePromise<void> {
    return $Call.ByID(2538605063, connID, topic);
}
