// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService 管理已保存的客户端连接档案（持久化到数据库）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * DeleteConnection 删除指定连接档案。
 */
export function DeleteConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(539279842, id);
}

/**
 * GetConnection 按 ID 获取单个连接档案。
 */
export function GetConnection(id: string): $CancellablePromise<models$0.Connection | null> {
    return $Call.ByID(1739289555, id);
}

/**
 * ListConnections 返回全部连接档案，按排序字段与创建时间升序。
 */
export function ListConnections(): $CancellablePromise<models$0.Connection[] | null> {
    return $Call.ByID(2605341254);
}

/**
 * SaveConnection 创建或更新连接档案。ID 为空时创建新记录并返回。
 * 时间戳完全由后端维护：新建时写入 CreatedAt/UpdatedAt，更新时保留原 CreatedAt、刷新 UpdatedAt。
 */
export function SaveConnection(input: models$0.ConnectionInput): $CancellablePromise<models$0.Connection | null> {
    return $Call.ByID(4241284660, input);
}
