// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppInfo 应用信息结构。
 */
export interface AppInfo {
    "name": string;
    "version": string;
    "buildHash": string;
    "buildTime": string;
}

/**
 * BrokerClientInfo 描述一个已连接客户端。
 */
export interface BrokerClientInfo {
    "clientId": string;
    "remote": string;
    "listener": string;
    "username": string;
    "clean": boolean;
    "protocol": number;
}

/**
 * BrokerConfig 是 broker 的可调参数。
 */
export interface BrokerConfig {
    "tcpEnabled": boolean;
    "tcpHost": string;
    "tcpPort": number;
    "wsEnabled": boolean;
    "wsHost": string;
    "wsPort": number;
    "allowAnonymous": boolean;
    "username": string;
    "password": string;
    "maxClients": number;
}

/**
 * BrokerEvent 是一条 broker 活动记录（连接、发布、订阅等）。
 */
export interface BrokerEvent {
    /**
     * connect | disconnect | subscribe | unsubscribe | publish
     */
    "type": string;
    "clientId": string;
    "remote": string;
    "topic": string;
    "payload": string;
    "qos": number;
    "retain": boolean;
    "detail": string;
    "timestamp": number;
}

/**
 * BrokerStats 是发送给前端的统计快照。
 */
export interface BrokerStats {
    "running": boolean;
    "startedAt": number;
    "uptime": number;
    "clientsConnected": number;
    "clientsTotal": number;
    "messagesReceived": number;
    "messagesSent": number;
    "bytesReceived": number;
    "bytesSent": number;
    "subscriptions": number;
    "retained": number;
    "inflight": number;
}

/**
 * BrokerStatus 是 broker 的整体状态。
 */
export interface BrokerStatus {
    "running": boolean;
    "startedAt": number;
    "config": BrokerConfig;
    "stats": BrokerStats;
}

/**
 * ClientConnectOptions 描述一次客户端连接所需的参数。
 */
export interface ClientConnectOptions {
    /**
     * tcp | tls | ws | wss
     */
    "protocol": string;
    "host": string;
    "port": number;
    "path": string;
    "clientId": string;
    "username": string;
    "password": string;
    "keepAlive": number;
    "cleanSession": boolean;

    /**
     * 3 = 3.1, 4 = 3.1.1
     */
    "mqttVersion": number;
    "tlsSkipVerify": boolean;
}

/**
 * ClientMessage 是推送给前端的一条 MQTT 消息。
 */
export interface ClientMessage {
    "connId": string;

    /**
     * received | published
     */
    "direction": string;
    "topic": string;
    "payload": string;
    "qos": number;
    "retain": boolean;
    "timestamp": number;
}

/**
 * ClientStatusEvent 是连接状态变化事件。
 */
export interface ClientStatusEvent {
    "connId": string;

    /**
     * connecting | connected | disconnected | error | reconnecting
     */
    "status": string;
    "detail": string;
    "timestamp": number;
}
