// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 通用键值设置服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * GetSetting 读取设置值，不存在时返回默认值（或空字符串）。
 */
export function GetSetting(key: string): $CancellablePromise<string> {
    return $Call.ByID(1630723932, key);
}

/**
 * SetSetting 写入设置值（upsert）。
 */
export function SetSetting(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(1326210248, key, value);
}
